trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: '.NET 8'
  inputs:
    packageType: sdk
    version: 8.x

- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: build
    arguments: --configuration Release

- task: DotNetCoreCLI@2
  displayName: 'Test solution'
  inputs:
    command: test
    arguments: --configuration Release
